Develop
TatyanaBogdanovich/Diplome_Monkkee_QA26_TanyaBogdanovich pull request #1
Opened 2024-08-19 07:10 UTC by TatyanaBogdanovich

2024-08-19 10:38 UTC, voropa requested changes

2024-08-19 10:38 UTC, voropa commented on pom.xml
> +        <suiteName>smoke</suiteName>
Почему у вас 2 строки подряд идет один и тот же параметр с одинаковым названием "suiteName"  - так точно должно быть?

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/BasePage.java
> +            foundAlert = true;
Можно упросить логику этого метода и обойтись без if():
try  {
wait.until(ExpectedConditions.alertIsPresent());
driver.switchTo().alert().accept();
} catch (TimeoutException ignored) {
        }

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    public String getAlertText() { //возвращает текст алерта
Коментарии к методам нужно писать либо над методом (на строку выше, как аннотация) либо на строку ниже, под заголовком метода

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    public static final By SELECT_DAY = By.xpath("//div[1]/table/tbody/tr[3]/td[5]");
Плохой локатор с индексами: //div[1]/table/tbody/tr[3]/td[5]- переделайте

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    public static final By EDIT_ENTRY = By.cssSelector("a.entry div.body");
Как это у двух элементов на странице одинаковый локатор: a.entry div.body?

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    public LoginPage clickLogoutButton() {
Почему @Step аннотация не над всеми методам в классе?

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +        Thread.sleep(3000);
Почему тут Thread.sleep()? - замените на явное ожидание

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    @Step("Ввести в поле календаря значение 16/15/2024")
Почему именно "16/15/2024" ? в этот метод же можно любое значение передать...

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    @Step("Проверить, что записи от 16 Aug. 2024")
Тот же вопрос с датой тут

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    public void getEntriesDate(String checkDate) {
Зачем в этом методе входной аргумент checkDate если он не используется?

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/EntriesPage.java
> +    public static final By EDIT_TABLE = By.id("editable");
Опять вопросы к локаторам, два элемента с локатором "editable" на одной странице

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/EntriesPage.java
> +        // Временное решение, которое должно быть заменено , на появленеие текста в поле URL
Замените Thread.sleep() на ожиждание.  Второй на строку выше тоже

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/EntriesPage.java
> +import static tests.BaseTest.DISPLAY_TEXT;
Зачем вамм в page-классе импорт переменной из test класса?

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    private static final By LOGIN_BUTTON = By.xpath("//button//div");
Плохой локатор, под него подходит любая кнопка на странице, она там одна?

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +        log.debug("changeLogin {} , {}", changeLogin, changePassword);
А почему тут у вас лог уровня debug?  А в методе выше info()

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    public void changeLogin(String changeLogin, String changePassword) {
А в чем вообще разница ммежду этим методом и методомм login() выше? Они же выполняют одинаковые действия...

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/SettingsPage.java
> +    public static final By SAVE_BUTTON = By.xpath("//*[@id='settings-content']/div/form/div[7]/div/button");
Плохой локатор: //*[@id='settings-content']/div/form/div[7]/div/button - переделайте / укоротите его

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/SettingsPage.java
> +    public static final By SUCCESS_MASSAGE = By.xpath("//*[@id='settings-content']/div/div/div");
Тут тоже /div/div/div

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +        driver.findElement(ERROR_LOGIN).isDisplayed();
А чего в этом page-классе не приеняете ппаттер chainOfInvvocations?

2024-08-19 10:38 UTC, voropa commented on src/test/java/pages/EntriesPage.java
> +    public void clickEditEntryTable() {
Такой же вопрос по  применению паттерна на этой странице. Если приименяете паттерн - то нужно применять его на всех страницах

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    public static String ENTER_TEXT_INPUT = "Редкие фото. Как выглядела улица Карла Маркса в 30-х годах.";
Можно и в BaseTest хранить тестовые данные. Но, если они у вас ипользуются в одном конкретном тест-классе - то будет логичнее хранить их там, а не захламлять BaseTest

2024-08-19 10:38 UTC, voropa commented on src/test/java/utils/DriverFactory.java
> +                EdgeOptions options1 = new EdgeOptions();
почему options1? Что мешает назвать переменную просто options?

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +        driver.manage().window().maximize();
ЗАчем дублировать эти действия (maximize() и implicitlyWait(Duration.ofSeconds(5));) ? Они уже есть внутри  метода getDriver() в DriverFactory

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +        driver.get("https://monkkee.com/app/#/");
А чего тут не берете URL из properties файла?

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +
Тут 6 пустых строк кода - отформатируйте

2024-08-19 10:38 UTC, voropa commented on src/test/resources/suites/smoke.xml
> +<suite name="Smoke test" parallel="classes" thread-count="1">
А чего thread-count = 1?

2024-08-19 10:38 UTC, voropa commented on src/test/resources/suites/smoke.xml
> +        <classes>
Зачем тут указывать <classes> если выше вы уже указали  <package name="tests"> - из него и так выберутся все тесты из всех классов

2024-08-19 10:38 UTC, voropa commented on src/test/resources/suites/negative.xml
> +<suite name="Positive Tests" parallel="classes" thread-count="2">
должно быть "Negative tests" ?

2024-08-19 10:38 UTC, voropa commented on src/test/resources/config.properties
> +changeLogin = alisa
Смысл исользования properties файла, чтобы не комитить реальные значения login / pass в пубьличный репозиторий на github, а оставлять их ппустыми и подставлять в этот файл локально, когда запускаете тесты...

2024-08-19 10:38 UTC, voropa commented on src/test/java/utils/TestListener.java
> +        ITestListener.super.onTestSuccess(result);
Зачем вам этот listener? он делает что-то полезное?

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/FilterEntriesDataTest.java
> +        loginPage.login(PropertyReader.getProperty("login"), PropertyReader.getProperty("password"));
А чего вы login() не вынесите в pre-condition (before) к тестам, чтобы не писать его каждый раз?

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/FilterEntriesDataTest.java
> +        dashboardPage.clickSelectDay();
Если метод  clickSelectDay() выбирает дату в календаре - то эта дата должна передаваться входным аргументом в метод

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/FilterEntriesDataTest.java
> +        Assert.assertTrue(dashboardPage.isDashboardDisplayed());
Не пониамю, а что этот тест  проверяет? вводит дату и смотрит, что dashBoard Displayed? А когда он НЕ displayed()?

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/EditEntryTest.java
> +    @Test(groups = "negative", description = "Редактировать запись")
Чего этот тест "negative"? Сценарий выглядит как positve...

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/DeleteEntriesTest.java
> +        Assert.assertTrue(dashboardPage.isDashboardDisplayed());
У вас почти во всех тестах проверки на (dashboardPage.isDashboardDisplayed() - но этого не достаточно. Для теста на удаление, например, нужно проверить, что такой записи / сущности больше нет в списке после удаления

2024-08-19 10:38 UTC, voropa commented on src/test/java/tests/CreateEntryTest.java
> +        Assert.assertEquals(dashboardPage.getCheckEntry(), enterTextInput);
У вас в трех тестах одряд создается запись с тектом ENTER_TEXT_INPUT. 
Если, например, во втором тесте что-то пойдет не так и запись не создастся - то тест все равно пройдет, так как предыдущий тест создал такую же запись и проверка пройдет. 

Сделайте тестовые данные уникальнвми для разных тестов. Используйте библиотеку  java-faker например

2024-08-19 10:47 UTC, TatyanaBogdanovich commented on src/test/java/tests/FilterEntriesDataTest.java
> +        Assert.assertTrue(dashboardPage.isDashboardDisplayed());
Задумка была проверить, что не валидная дата не сохраняется в фильтр.  Я ожидала какой то ошибки.... а тут ее не было, поэтому добавила просто dashBoard Displayed - отображение главной станицы без изменений. 
Согласна, что не очень удачная проверка.

2024-08-19 11:34 UTC, TatyanaBogdanovich commented on pom.xml
> +        <suiteName>smoke</suiteName>
fix

2024-08-19 11:34 UTC, TatyanaBogdanovich commented on src/test/java/pages/BasePage.java
> +            foundAlert = true;
fix

2024-08-19 11:34 UTC, TatyanaBogdanovich commented on src/test/java/pages/BasePage.java
> +    public String getAlertText() { //возвращает текст алерта
fix

2024-08-19 11:34 UTC, TatyanaBogdanovich commented on src/test/java/pages/DashboardPage.java
> +    public static final By SELECT_DAY = By.xpath("//div[1]/table/tbody/tr[3]/td[5]");
fix

2024-08-19 11:34 UTC, TatyanaBogdanovich commented on src/test/java/pages/DashboardPage.java
> +    public static final By EDIT_ENTRY = By.cssSelector("a.entry div.body");
Объединила в один.

2024-08-19 11:34 UTC, TatyanaBogdanovich commented on src/test/java/pages/DashboardPage.java
> +    public LoginPage clickLogoutButton() {
fix

2024-08-19 11:34 UTC, TatyanaBogdanovich commented on src/test/java/pages/DashboardPage.java
> +        Thread.sleep(3000);
fix

2024-08-19 11:36 UTC, TatyanaBogdanovich commented on src/test/java/pages/DashboardPage.java
> +    @Step("Ввести в поле календаря значение 16/15/2024")
Заменила название метода на "Проверка ввода не валидного формат даты"

2024-08-19 11:38 UTC, TatyanaBogdanovich commented on src/test/java/pages/DashboardPage.java
> +    @Step("Проверить, что записи от 16 Aug. 2024")
Заменила на "Проверка отображения записей согласно установленному фильтру"

2024-08-19 11:47 UTC, TatyanaBogdanovich commented on src/test/java/pages/DashboardPage.java
> +    public void getEntriesDate(String checkDate) {
fix

2024-08-19 11:51 UTC, TatyanaBogdanovich commented on src/test/java/pages/EntriesPage.java
> +    public static final By EDIT_TABLE = By.id("editable");
fix

2024-08-19 12:52 UTC, TatyanaBogdanovich commented on src/test/java/pages/EntriesPage.java
> +        // Временное решение, которое должно быть заменено , на появленеие текста в поле URL
вроде получилось с неявным ожиданием)
![image](https://github.com/user-attachments/assets/d77340d7-b71c-4f7c-996c-5a9b6d518c78)

2024-08-19 12:54 UTC, TatyanaBogdanovich commented on src/test/java/pages/EntriesPage.java
> +import static tests.BaseTest.DISPLAY_TEXT;
fix

2024-08-19 12:59 UTC, TatyanaBogdanovich commented on src/test/java/pages/LoginPage.java
> +    private static final By LOGIN_BUTTON = By.xpath("//button//div");
Да, она там одна на всю страницу) Но можно и другой использовать -By.xpath("//button[@type='submit']");
![image](https://github.com/user-attachments/assets/3fc3030b-8cb4-4e8c-a4b1-1d92981f1394)

2024-08-19 13:03 UTC, TatyanaBogdanovich commented on src/test/java/pages/LoginPage.java
> +        log.debug("changeLogin {} , {}", changeLogin, changePassword);
Ошиблась. fix

2024-08-19 13:04 UTC, TatyanaBogdanovich commented on src/test/java/pages/LoginPage.java
> +    public void changeLogin(String changeLogin, String changePassword) {
У них разные тестовые данные

2024-08-19 13:12 UTC, TatyanaBogdanovich commented on src/test/java/pages/SettingsPage.java
> +    public static final By SAVE_BUTTON = By.xpath("//*[@id='settings-content']/div/form/div[7]/div/button");
fix 
By.xpath("//button[@class='btn btn-default']")
By.xpath("//button[@type='submit']")

2024-08-19 13:19 UTC, TatyanaBogdanovich commented on src/test/java/pages/SettingsPage.java
> +    public static final By SUCCESS_MASSAGE = By.xpath("//*[@id='settings-content']/div/div/div");
fix - //div[@class='alert alert-success']
![image](https://github.com/user-attachments/assets/e84d19b3-830e-4f8d-b1c6-582239b2bee7)

2024-08-19 13:20 UTC, TatyanaBogdanovich commented on src/test/java/tests/BaseTest.java
> +    public static String ENTER_TEXT_INPUT = "Редкие фото. Как выглядела улица Карла Маркса в 30-х годах.";
Исправить или взять на заметку на будущее?

2024-08-19 13:26 UTC, TatyanaBogdanovich commented on src/test/java/utils/DriverFactory.java
> +                EdgeOptions options1 = new EdgeOptions();
Потому , что options - для хрома, а options1 - для Edge

2024-08-19 13:27 UTC, TatyanaBogdanovich commented on src/test/java/tests/BaseTest.java
> +        driver.manage().window().maximize();
fix

2024-08-19 13:30 UTC, TatyanaBogdanovich commented on src/test/java/tests/BaseTest.java
> +        driver.get("https://monkkee.com/app/#/");
fix - driver.get(PropertyReader.getProperty("baseUr)l"));

2024-08-19 13:31 UTC, TatyanaBogdanovich commented on src/test/java/tests/BaseTest.java
> +
fix

2024-08-19 13:32 UTC, TatyanaBogdanovich commented on src/test/resources/suites/smoke.xml
> +<suite name="Smoke test" parallel="classes" thread-count="1">
fix - исправила на 2.

2024-08-19 13:35 UTC, TatyanaBogdanovich commented on src/test/resources/suites/smoke.xml
> +        <classes>
fix

2024-08-19 13:36 UTC, TatyanaBogdanovich commented on src/test/resources/suites/negative.xml
> +<suite name="Positive Tests" parallel="classes" thread-count="2">
даааа,  fix

2024-08-19 13:37 UTC, TatyanaBogdanovich commented on src/test/resources/config.properties
> +changeLogin = alisa
да, помню, ты об этом говорил на лекции, копировать и хранить локально на компьютере. Забыла вырезать.

2024-08-19 13:41 UTC, TatyanaBogdanovich commented on src/test/java/utils/TestListener.java
> +        ITestListener.super.onTestSuccess(result);
удобно в консоли отслеживать статус тестов.
![image](https://github.com/user-attachments/assets/d6983c54-8961-43be-8725-f2af7267756b)

2024-08-19 13:52 UTC, TatyanaBogdanovich commented on src/test/java/tests/EditEntryTest.java
> +    @Test(groups = "negative", description = "Редактировать запись")
positve... fix

2024-08-19 14:27 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    public static String ENTER_TEXT_INPUT = "Редкие фото. Как выглядела улица Карла Маркса в 30-х годах.";
лучше исправить

2024-08-19 14:29 UTC, voropa commented on src/test/java/utils/DriverFactory.java
> +                EdgeOptions options1 = new EdgeOptions();
Вроде ничего не мешает назвать эти переменные одинаково, просто options. Они же в разных case блоках находятся, не пересекаются по области видимости.
<img width="604" alt="image" src="https://github.com/user-attachments/assets/4cd772ff-c3bf-4dea-a9cf-7792b6fd3864">

2024-08-19 14:30 UTC, voropa commented on src/test/java/utils/TestListener.java
> +        ITestListener.super.onTestSuccess(result);
Ок, тогда замените хотя бы system.out() на log.info() / debug()

2024-08-19 16:53 UTC, TatyanaBogdanovich commented on src/test/java/pages/LoginPage.java
> +        driver.findElement(ERROR_LOGIN).isDisplayed();
fix
Page классы  переделала в соответствии с паттерном.

2024-08-19 16:53 UTC, TatyanaBogdanovich commented on src/test/java/pages/EntriesPage.java
> +    public void clickEditEntryTable() {
fix
Page классы  переделала в соответствии с паттерном.

2024-08-19 16:57 UTC, TatyanaBogdanovich commented on src/test/java/tests/BaseTest.java
> +    public static String ENTER_TEXT_INPUT = "Редкие фото. Как выглядела улица Карла Маркса в 30-х годах.";
fix

2024-08-19 17:02 UTC, TatyanaBogdanovich commented on src/test/java/utils/DriverFactory.java
> +                EdgeOptions options1 = new EdgeOptions();
А у меня ругается Idea.
![image](https://github.com/user-attachments/assets/f568fe36-a8e2-48fd-aa98-77ffaba757cc)

2024-08-19 17:06 UTC, TatyanaBogdanovich commented on src/test/java/utils/DriverFactory.java
> +                EdgeOptions options1 = new EdgeOptions();
Интересно, изменила синтаксис - все Ок
![image](https://github.com/user-attachments/assets/1223ace1-95b6-42a0-86fd-d6e73298edf8)

2024-08-19 17:43 UTC, TatyanaBogdanovich commented on src/test/java/utils/TestListener.java
> +        ITestListener.super.onTestSuccess(result);
fix

2024-08-20 10:10 UTC, voropa requested changes

2024-08-20 10:10 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    public static final By SELECT_DAY = By.xpath("//div[contains(@class, 'datepicker-days')]//tbody//td[contains(., '16')]");
Почему тут захардкодано число 16? Это должно передаваться входным аргументом в метод, чтобы была возможность выбрать любую дату. Переделайте, используйте шаблонную строку для локатора, например

2024-08-20 10:10 UTC, voropa commented on src/test/java/pages/EntriesPage.java
> +        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
А какой смысл от того, что вы тут увеличиваете implicitly wait timeout? Это же не явное ожидание, оно тут ничего ждать не будет...

2024-08-20 10:10 UTC, voropa commented on src/test/resources/config.properties
> -base.url=https://monkkee.com/app/#/
Не нужно полностью очищать .properties файл. Будет же непонятно какие сюда нужно переменные добавить. Лучше делать так:
base.url=<ENTER VALUE HERE>
#global test data
login = <ENTER VALUE HERE>
password = <ENTER VALUE HERE>

2024-08-20 10:13 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    @Step("Ввести в поле календаря значение 16/15/2024")
Хмм, но метод же ничего не проыеряет, а вводит дату в поле ввода. Соотвественно и степ / log должен называться "ввести что-то куда-то.."

2024-08-20 10:13 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    @Step("Проверить, что записи от 16 Aug. 2024")
see comment above

2024-08-20 10:16 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    @Step("Проверка отображения записей согласно установленному фильтру")
А что делать этот метод вообще? он берет текст и не возвращает его, а делает return this...

2024-08-20 10:16 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    public void changeLogin(String changeLogin, String changePassword) {
Всмысле разные тестовые данные? Тестовые данные поступпают сюда в виде входных аргументов типа String loggin, String password. Сюда можно передавать любые данные. 
2 метода просто одинаковых, прост ос разными названиями, зачем?

2024-08-20 10:18 UTC, voropa commented on src/test/java/tests/FilterEntriesDataTest.java
> +        Assert.assertTrue(dashboardPage.isDashboardDisplayed());
Нужно улучшить / придумать другую проверку для этого теста

2024-08-20 20:21 UTC, TatyanaBogdanovich commented on src/test/java/pages/LoginPage.java
> +    public void changeLogin(String changeLogin, String changePassword) {
fix  убрала дублирующий метод
![image](https://github.com/user-attachments/assets/2ac315eb-bc76-4f3d-9f71-ec508b674947)

2024-08-20 21:40 UTC, TatyanaBogdanovich commented on src/test/java/tests/FilterEntriesDataTest.java
> +        loginPage.login(PropertyReader.getProperty("login"), PropertyReader.getProperty("password"));
fix - вынесла в  в pre-condition
![image](https://github.com/user-attachments/assets/cc2f3d03-5ece-4c02-8192-080e1b83c7f0)
![image](https://github.com/user-attachments/assets/f62bcb4c-3085-45e5-b669-39a9d4f48be6)

2024-08-20 21:49 UTC, TatyanaBogdanovich commented on src/test/java/pages/EntriesPage.java
> +        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
fix

2024-08-20 21:51 UTC, TatyanaBogdanovich commented on src/test/resources/config.properties
> -base.url=https://monkkee.com/app/#/
fix

2024-08-20 21:59 UTC, TatyanaBogdanovich commented on src/test/java/pages/DashboardPage.java
> +    @Step("Проверка отображения записей согласно установленному фильтру")
fix

2024-08-22 17:49 UTC, TatyanaBogdanovich commented on src/test/java/tests/CreateEntryTest.java
> +        Assert.assertEquals(dashboardPage.getCheckEntry(), enterTextInput);
fix 
Использовала библиотеку java-faker для всех 3-х тестов.
![image](https://github.com/user-attachments/assets/bc3dfa36-3bfe-465e-9616-dc383ccc0967)
![image](https://github.com/user-attachments/assets/c16914fb-4afd-4a79-be48-8d0357981902)

2024-08-22 21:00 UTC, TatyanaBogdanovich commented on src/test/java/tests/FilterEntriesDataTest.java
> +        Assert.assertTrue(dashboardPage.isDashboardDisplayed());
fix

2024-08-25 11:58 UTC, voropa requested changes

2024-08-25 11:58 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    @Step("Проверка отображения записей согласно установленному фильтру")
Все равно не понимаю что делает этот метод и зачем он

2024-08-25 11:58 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    @Step("Количество всех записей")
Это неправильно, вспоминай, что мы обсуждали на звонке. Для получения количества записей нужно испольщовать driver.findElements(enntriesLOcator).size()

2024-08-25 11:58 UTC, voropa commented on src/test/java/pages/EntriesPage.java
> +                break;
А в конце этого метода разве не нужно переключатся обратно на mainWindowHandle? А то тест дальше не пойдет выполняться, так как фокус драйвера на новой вкладке остался

2024-08-25 11:58 UTC, voropa commented on src/test/java/pages/SettingsPage.java
> +    public void changePassword(String oldPassword, String newPassword, String repeatPassword, String hintPassword) {
А почему тут поменяли return type на Void?

2024-08-25 11:58 UTC, voropa commented on src/test/java/pages/SettingsPage.java
> +       //явное ожидание в данном методе не помогает
Почему не работает, какое ожидание пробовали исользовать?

2024-08-25 11:58 UTC, voropa commented on src/test/java/tests/LoginTest.java
> +    @Test(groups = {"userLogin", "regression", "smoke"}, description = "Успешная авторизация в приложении")
Для Llgin теста как раз таки имее тсмыс л не добавлять группу "userLogin", а пропписать шаг с логином внутри теста, чтобы было нагляднее. А то тест состоит только из проверки

2024-08-25 11:58 UTC, voropa commented on src/test/java/tests/PrintEntryTest.java
> +        Assert.assertTrue(entriesPage.verifyWindowPrint());
Добавьте проверку на текст/ дату записи, которая открывается в новом окне для печати

2024-08-25 11:58 UTC, voropa commented on src/test/java/tests/SearchEntriesTest.java
> +    @Test(groups = {"userLogin", "smoke"}, description = "Создать запись + добавить картинку из файла")
description не соответсвует шагам  теста

2024-08-25 11:58 UTC, voropa commented on src/test/java/tests/SearchEntriesTest.java
> +        dashboardPage.getEntriesDate();
А для чего вызывать этот метод  getEntriesDate(), что он делает?

2024-08-26 18:10 UTC, voropa requested changes

2024-08-26 18:10 UTC, voropa commented on src/test/java/pages/EntriesPage.java
> +    public static final By INPUT_CONTAINER = By.xpath("//table[@class='cke_dialog_ui_hbox cke_dialog_image_url']");
Кажется, это свойство INPUT_CONTAINER нигде не используется - удалите его

2024-08-26 18:10 UTC, voropa commented on src/test/java/pages/NewWindowPage.java
> +public class NewWindowPage extends BasePage {
Почему NewWindowPage? Назовите хотя бы PrintEntryPage

2024-08-26 18:10 UTC, voropa commented on src/test/java/pages/NewWindowPage.java
> +    public String isDateEntryDisplayed() {
С нэймнгом методов у вас что-то не совсем понятное мне) 
Метод называется is...Displayed(), а возвращает String. По логике вещей он тогда должен называться get....Text()

2024-08-26 18:10 UTC, voropa commented on src/test/java/pages/NewWindowPage.java
> +    @Step("Проверка отображения текста записи в новом окне")
Тут тоже

2024-08-26 18:10 UTC, voropa commented on src/test/java/pages/DashboardPage.java
>      public String getCheckEntry() {
Вот тут я тоже не пониммамю что делает метод по его названию. getCheckEntry() возвращает String текст, но потом  в тесте, например, вы его вызываете и не используете реузльтат (String), который метод возвращает. Тогда зачем его вызывать, в чем задумка?
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/2ea8a4d9-e2ff-4f6e-b959-ae8ee0e1b398">

2024-08-26 18:10 UTC, voropa commented on src/test/java/tests/PrintEntryTest.java
> +        String  mainDateEntry = driver.findElement(By.xpath("//time[@class = 'ng-binding']")).getText();
Это что такое? почему в тесте driver и локаторы? Вынесите в page методы

2024-08-27 08:04 UTC, voropa requested changes

2024-08-27 08:04 UTC, voropa commented on src/test/java/pages/SettingsPage.java
> +        } catch (Exception exception) {
Во-первых нужно отлавливать конкретный exception, который ElementClickInterceptedException, а в не любой попавшийся. 
Во-вторых, с такой логикой, даже если клик не пройдет 2 раза подряд, то в последнем блоке catch он проосто проигноррируется, тест пойдет дальше и уапдет с ошибкой на следующем шаге. 
Так что нужно во второй catch  все же обрабатывать как-то и фэйлить тест, если не прошел клик, нарпимер, throw new Exception("Can't click logout button");

2024-08-27 08:04 UTC, voropa commented on src/test/java/pages/SettingsPage.java
> +            } catch (Exception exception1) {
почему exception1? У него же своя область видимости внутри catch

2024-08-27 10:01 UTC, voropa approved these changes

2024-08-27 13:03 UTC, merged